export interface Article {
    id:number
    title:string
    alias:string
    description:string
    author:string
    image:string
    content:string
    category:string
    language_id:number
    language:string
    status:number
    recent:number
    feature:number
    popular:number
    how:number
    published:number
    created_at:Date
    updated_at:Date
}
