export interface Article {
    id:number
    title?:string
    alias?:string
    description?:string
    author_id?:number
    image?:string
    content_id?:number
    category_id?:number
    language_id?:number
    status?:number
    recent?:number
    feature?:number
    popular?:number
    how?:number
    published?:number
    created_at?:Date
    updated_at?:Date
    deleted_at?:Date
}
